### PR TITLE
Fix sticky table header can't scroll with its body in horizontal direction

### LINKED ISSUE #462: CardTableV2 sticky header can't scroll in horizontal direction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

51_origin

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

### PR DESCRIPTION
**Pull request by baurine**
fix #462 

What did:

- Fix the bug that sticky table header can't scroll with the body in the horizontal direction

The original situation:

51_origin

According to the issue: https://github.com/microsoft/fluentui/issues/7742 , the easiest way is to just set `constrainMode={ConstrainMode.unconstrained}` for DetailsList. This makes the sticky table header scrolls with its body but makes the sticky toolbar scrolls as well (same as the official demo), I don't think it is expected.

48_solution_1

So I only wrap the table instead of the root container by `<ScrollablePane>`.

49_solution_2

But the margin collapse doesn't work anymore, it makes the sticky table header jumping when it switches between sticky or not.

Adding another new props `noMarginTop` to remove the additional margin-top, maybe not very elegant, doesn't know whether it has some better ideas. (still a little jumping but much better than above)

Final effect:

52_solution_final

### CODE REVIEW

File: ui/lib/apps/SlowQuery/pages/List/index.tsx [hunk 1]
```diff
@@ -67,98 +66,97 @@ function List() {
...
-        slowQueries={slowQueries}
-        orderBy={orderOptions.orderBy}
-        desc={orderOptions.desc}
-        showFullSQL={showFullSQL}
-        visibleColumnKeys={visibleColumnKeys}
-        onGetColumns={setColumns}
-        onChangeOrder={changeOrder}
-      />
-    </ScrollablePane>
+      <div style={{ height: '100%', position: 'relative' }}>
```
Comment (breeswish) [inline ui/lib/apps/SlowQuery/pages/List/index.tsx:144]: will this 100% lead to extra space in the vertical direction?

**Comment by breeswish** [comment]
For the "This makes the sticky table header scrolls with its body but makes the sticky toolbar scrolls as well" issue, how about setting `isScrollSynced` to false (i.e. remove it)?

**Comment by baurine** [comment]
> For the "This makes the sticky table header scrolls with its body but makes the sticky toolbar scrolls as well" issue, how about setting `isScrollSynced` to false (i.e. remove it)?

Tried but doesn't work.

File: ui/lib/apps/SlowQuery/pages/List/index.tsx (hunk 1 above)
Comment (baurine) [reply ui/lib/apps/SlowQuery/pages/List/index.tsx:144]: Tested but it does not. This div is required for `ScrollablePane`, it needs a relative position parent, and must set height or max-height for itself or its parent.

Comment (baurine) [reply ui/lib/apps/SlowQuery/pages/List/index.tsx:144]: Let me have a test.

Comment (baurine) [reply ui/lib/apps/SlowQuery/pages/List/index.tsx:144]: Yep, it will lead to some extra space on the page bottom if there are no much data, but I think it is acceptable currently.

image
