### PR TITLE
ui: remove experimental API in checkBrowser.js

### LINKED ISSUE #770: Check browerlist whether really works
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Access dashboard in Chrome 5x version.

**What did you expect to see?**

Work normally.

**What did you see instead?**

It crashes and says `Object.entries()` is not a function.

(This version of Chrome is supported in the browser list, so the checkBrowser.js doesn't show a prompt to say this browser version is too low.)

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

4.0.7

### PR DESCRIPTION
**Pull request by unbyte**
image

---

close #770 

when testing the related issue on the low version of the Firefox, we found that alert from checkBrowser.js can't appear for the experimental API checkBrowser.js uses is not supported by these low version browsers.

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]

File: ui/public/checkBrowser.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ function checkBrowser() {
     d.getElementsByTagName('a')[0].onclick = function () {
       d.getElementsByTagName('div')[0].style.top = '-60px'
     }
-    document.body.prepend(d)
+    document.body.prepend ? document.body.prepend(d) : document.body.insertBefore(d, document.body.firstChild)
```
Comment (baurine) [inline ui/public/checkBrowser.js:43]: I prefer to directly use `document.body.insertBefore(d, document.body.firstChild)`.

We can use 1 PR to resolve the problems of #770 together (will discuss it later).

**Comment by baurine** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/ParentNode/prepend

prepend can be used in chrome 54+, edge 17+, Firefox 49+

File: ui/public/checkBrowser.js (hunk 1 above)
Comment (unbyte) [reply ui/public/checkBrowser.js:43]: yeah, however, the support for `firstChild` in chromes <=85 is unknown as caniuse shows

Comment (baurine) [reply ui/public/checkBrowser.js:43]: It doesn't matter, according to this doc: https://developer.mozilla.org/zh-CN/docs/Web/API/Node/insertBefore , even if firstChild exist or not, insertBefore will work fine.

Comment (kennytm) [reply ui/public/checkBrowser.js:43]: how about `childNodes[0]`.

but i highly doubt Chrome 85- *not* supporting `firstChild` which is in DOM 1 released back in 1997.

Comment (unbyte) [reply ui/public/checkBrowser.js:43]: just curious about why support is unknown. maybe there is a special reason?

Comment (baurine) [reply ui/public/checkBrowser.js:43]: I think it is fine, according to this doc: https://developer.mozilla.org/zh-CN/docs/Web/API/ParentNode/prepend , `prepend` polyfill is implemented by `insertBefore` and `firstChild`, even if `document.body.firstChild` is undefined, it works as expected, or we can consider using `appendChild`?

Comment (unbyte) [reply ui/public/checkBrowser.js:43]: `unknow` comes from no real data yet. see https://github.com/mdn/browser-compat-data/issues/6369
so yeah we can use `insertBefore` directly

**Comment by unbyte** [comment]
since Firefox 46 is not in our support list, dashboard still can't work in it. However, alert works well now.
image

**Review by baurine — APPROVED** [review]
LGTM
