### PR TITLE
ignore empty log searching results

### LINKED ISSUE #492: Do not produce slow log archive if there is no slow log
## Bug Report

image

Now we will have an empty slow log archive even if there is no slow log. This is pretty confusing.

### PR DESCRIPTION
**Pull request by Fullstop000**
UCP https://github.com/pingcap-incubator/tidb-dashboard/issues/507
Fix #492

Also, disable the tree node in log searching progress sidebar if the related task fails or has no searching results

Signed-off-by: Fullstop000 <fullstop1005@gmail.com>

### CODE REVIEW

File: ui/lib/apps/SearchLogs/components/SearchProgress.tsx [hunk 1]
```diff
@@ -13,26 +13,16 @@ import styles from './Styles.module.css'
...
-      return {
-        icon: FailIcon,
-        disableCheckbox: true,
-      }
-    default:
-      break
+function leafNodeProps(task: LogsearchTaskModel) {
+  return {
+    icon: taskStateIcons[task.state || TaskState.Error],
+    disableCheckbox: task.size ? task.state !== TaskState.Finished : true,
```
Comment (breeswish) [inline ui/lib/apps/SearchLogs/components/SearchProgress.tsx:25]: `disableCheckbox: !task.size || task.state !== TaskState.Finished`?

File: pkg/apiserver/logsearch/task.go [hunk 2]
```diff
@@ -131,6 +131,21 @@ func (t *Task) setError(err error) {
 	t.model.Error = &errStr
 }
 
+func (t *Task) accumulateLogSize(dir *string) {
```
Comment (breeswish) [inline pkg/apiserver/logsearch/task.go:134]: maybe call it `path` is better.
