### PR TITLE
cancel to generate ui library

### LINKED ISSUE #685: `yarn build:library` doesn't work anymore
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**What did you do?**

Run `yarn build:library` command in the `ui` folder to build the library.

**What did you expect to see?**

Build successfully.

**What did you see instead?**

Build failed. 

It said can't find `.package_release_version` file which is mis-deleted in PR #679 . Adding this file back can resolve this issue.   

Because DBass doesn't need the library anymore, do we need to remove it or still keep it for the future usage (likes for the plugin? maybe) @breeswish 

**What version of TiDB Dashboard are you using (`./tidb-dashboard --version`)?**

master branch.

### PR DESCRIPTION
**Pull request by baurine**
close #685 

Remove all codes about generating ui library since we don't need it anymore.

### CODE REVIEW

File: ui/config-overrides.js [hunk 1]
```diff
@@ -7,24 +7,13 @@ const {
...
   addDecoratorsLegacy,
   addBundleVisualizer,
-  addBabelPlugin,
   getBabelLoader,
 } = require('customize-cra')
 const addYaml = require('react-app-rewire-yaml')
 const { alias, configPaths } = require('react-app-rewire-alias')
 const webpack = require('webpack')
 const WebpackBar = require('webpackbar')
-const nodeExternals = require('webpack-node-externals')
```
Comment (breeswish) [inline ui/config-overrides.js:17]: dependencies can be cleaned up as well

Comment (baurine) [reply ui/config-overrides.js:17]: Yep, will do it soon.
